### ISSUE TITLE
Go back/edit previous worked on cluster

### ISSUE THREAD

**Issue by trevormunoz** [trevormunoz/ssmmfm#5]
- Turn the index terms in the list into links
- ~~Link should be modeled on the link that launches the exemplar~~
- Clicking link should re-load the relevant cluster in the pickListView
- Clicking the link triggers an event
- pickListView should listen for this new event and ...
-  pickListView loads up the cluster

**Comment by trevormunoz** [comment]
Add key binding to go back to the immediate previous cluster?

Add key binding to go back to any term in the list?

**Comment by katierawson** [comment]
We've decided to add a key binding to go back to the immediate previous cluster but not any cluster.

**Comment by trevormunoz** [comment]
Closed by 3347243 and 96c853f
